### ISSUE TITLE
RSS feed doesn't have unique IDs

### ISSUE THREAD

**Issue by ksuther** [lwkd/lwkd.github.io#10]
The id of each of the updates in the RSS feed aren't unique, causing RSS readers to not show the feed properly: `http://lwkd.info/2018/update`

(Initially reported as a Feedbin issue: https://github.com/feedbin/support/issues/586)

**Comment by coderanger** [comment]
Thanks for the report! Jekyll is weird about how it generates post IDs but we'll get this fixed shortly.
