### ISSUE TITLE
add email subscription options

### ISSUE THREAD

**Issue by jberkus** [lwkd/lwkd.github.io#2]
Folks want an email subscription to LWKD.  

Not sure the best way to handle this.  I could create a mailing list, or I could write an ad-hoc email blast script.  Possibly there's something better out there?

**Comment by mareklibra** [comment]
It might be sufficient to just `watch` this repository (button on the top of the repo home page)

**Comment by jberkus** [comment]
No, folks have specifically asked for email, which seems reasonable enough.

**Comment by jberkus** [comment]
We are now doing email subscription via MailChimp.
