### ISSUE TITLE
Add web analytics to LWKD

### ISSUE THREAD

**Issue by jberkus** [lwkd/lwkd.github.io#3]
... because it would be nice to know how many readers we have.

However, doing this seems to require moving off pure Github Pages.  No?

**Comment by fabiand** [comment]
No, I don't think so. I think you just need to include a script snippet.

**Comment by coderanger** [comment]
This is doable, but we would have to copy the `default.html` layout over from the theme to customize it. But that's pretty standard and should be fine.

**Comment by coderanger** [comment]
Check that, the default template already has google analytics set up, https://github.com/pages-themes/minimal/blob/master/_layouts/default.html#L59

**Comment by jberkus** [comment]
Huh, any idea how I access that?

**Comment by coderanger** [comment]
Add `google_analytics: [Your Google Analytics tracking ID]` to the config.yml. I can set up a GA account if you don't have one already (and tell me your google account to invite).

**Comment by jberkus** [comment]
Done, works, thanks!
