### ISSUE TITLE
Find coeditor

### ISSUE THREAD

**Issue by jberkus** [lwkd/lwkd.github.io#8]
I could really use another editor for LWKD, so that it still gets published during conference weeks.

Volunteers?

**Comment by onorua** [comment]
How do you track all the thing needs to be in? I mean I could try doing that, but not really sure I will not miss anything important.

**Comment by jberkus** [comment]
I pretty much comb through github notifications for the week.  It's not terribly complicated.

**Comment by coderanger** [comment]
I already watch the `features` repo pretty closely so I can definitely do some writeups from that info while you're out of commission (or just want you want a well-earned break).
